dist: trusty
language: node_js
node_js:
   - "8.1.4"
sudo: true

notifications:
  slack: miturbanrisklab:4y7wfdHde8dtfb00wTfNZfTA

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

branches:
  only:
    - master
    - dev
    - jsdocsToS3
    - server-object-refactor
    - report-archive

before_install:
  - npm i -g npm@5.0.3
  - if [[ $TRAVIS_BRANCH != 'master' ]]; then BRANCH='dev'; else BRANCH='master'; fi;
  - export PGDATABASE=cognicity_server_testing ; git clone -b $BRANCH https://github.com/urbanriskmap/cognicity-schema.git urbanriskmap/cognicity-schema && cd urbanriskmap/cognicity-schema && bash build/run.sh && cd -

install:
  - npm install

after_success: npm run coverage

deploy: #build the docs for dev branch only?
  provider: s3
  bucket: "dev-cognicity-server-docs"
  region: "us-east-1"
  access_key_id: $AWS_S3_ACCESS_KEY_ID
  secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
  skip_cleanup: true
  on:
    branch: jsdocsToS3
